name: PR Description check
on: [push, description]
jobs:
  PR-description-check:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce Pull Request Description Length
        uses: ryanvade/enforce-pr-description-length-action@v1
        with:
          minLength: 4
